### ISSUE TITLE
Maintenance Edit

### ISSUE THREAD

**Issue by madeleineworrall** [PrimitiveSocial/LubNeurosurgey#1]
@jeter 
- [x] Add Employee Bio/Headshot 

**Info Below**
Thomas R. Windisch
Headshot: ![Windisch,Thomasclr](https://user-images.githubusercontent.com/52709163/71373958-968ab080-257e-11ea-9841-1892cac511e4.jpg)
Bio: [Document1.docx](https://github.com/PrimitiveSocial/LubNeurosurgey/files/4013236/Document1.docx)

- [x] Add this new bio next to this guy 

<img width="286" alt="Screen Shot 2019-12-31 at 12 52 01 PM" src="https://user-images.githubusercontent.com/52709163/71631118-87ce7a00-2bcc-11ea-919e-154089f47594.png">

- [x] and update this paragraph below with the new name 

**Meet the Providers**
Mark D. D’Alise, MD, DMD, FACS; Harold K. Smith, MD; Jonathan P. Mannas, MD; and Robert A. Scranton, MD; and **Thomas R. Windisch**, MD are accepting appointments... blah blah blah

**Comment by jetercotton** [comment]
@madeleineworrall I believe we just need the name and the bio, then we'll be ready to move forward with this issue.

**Comment by madeleineworrall** [comment]
The name is above. He's working on getting us the bio but for now please include the information that I provided :) 

Thanks!

**Comment by jetercotton** [comment]
Sorry, I guess I'm missing it, but I'm not seeing this doctor's name within this issue. It's not Chad :)

**Comment by madeleineworrall** [comment]
Hey! This is updated with a bio and the name of the doctor :)

**Comment by jetercotton** [comment]
@madeleineworrall Thanks for providing! We'll get it plugged in.

**Comment by matthewPrimitive** [comment]
https://lubbockneurosurgery.com/ @jetercotton @madeleineworrall This is done

**Comment by matthewPrimitive** [comment]
@jetercotton wait one second

**Comment by matthewPrimitive** [comment]
@jetercotton okay i forgot to edit that pgraph done now

**Comment by jetercotton** [comment]
- [ ] Windisch Bio overlap:
![image](https://user-images.githubusercontent.com/45576954/71634125-f61c3800-2bde-11ea-92f0-864dc8051567.png)

After that, we're good to close the issue.

**Comment by matthewPrimitive** [comment]
@jetercotton ahh dang ok this site is hard coded bad i will find a way to fix that. In the future tho since these bios are in a densed area the client should make them shorter for them to appear more clean

**Comment by jetercotton** [comment]
@matthewPrimitive Of course. Let me know if there's any way I can help to get that resolved!
